//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="appIteratorFirst" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appIteratorLast" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appIteratorPrevious" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appIteratorNext" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appIteratorLabelArea" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="appIteratorDropDownList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="showIcon" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="width" use="required" type="{http://developer.cognos.com/schemas/report/11.0/}CSSFixedLength" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="appIteratorLabelText">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="textColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="appDotsPageIndicator">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="dotColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" default="gray" />
 *                           &lt;attribute name="activeDotColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" default="white" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="appIteratorNumber">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="textColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" />
 *                           &lt;attribute name="beforeText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="verticalType" default="number">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="number"/>
 *                                 &lt;enumeration value="lowerCaseRoman"/>
 *                                 &lt;enumeration value="upperCaseRoman"/>
 *                                 &lt;enumeration value="range"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="verticalRangeSeparator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="afterText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "appIteratorUI")
public class AppIteratorUI {

    protected AppIteratorUI.AppIteratorFirst appIteratorFirst;
    protected AppIteratorUI.AppIteratorLast appIteratorLast;
    protected AppIteratorUI.AppIteratorPrevious appIteratorPrevious;
    protected AppIteratorUI.AppIteratorNext appIteratorNext;
    protected AppIteratorUI.AppIteratorLabelArea appIteratorLabelArea;

    /**
     * Gets the value of the appIteratorFirst property.
     * 
     * @return
     *     possible object is
     *     {@link AppIteratorUI.AppIteratorFirst }
     *     
     */
    public AppIteratorUI.AppIteratorFirst getAppIteratorFirst() {
        return appIteratorFirst;
    }

    /**
     * Sets the value of the appIteratorFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppIteratorUI.AppIteratorFirst }
     *     
     */
    public void setAppIteratorFirst(AppIteratorUI.AppIteratorFirst value) {
        this.appIteratorFirst = value;
    }

    /**
     * Gets the value of the appIteratorLast property.
     * 
     * @return
     *     possible object is
     *     {@link AppIteratorUI.AppIteratorLast }
     *     
     */
    public AppIteratorUI.AppIteratorLast getAppIteratorLast() {
        return appIteratorLast;
    }

    /**
     * Sets the value of the appIteratorLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppIteratorUI.AppIteratorLast }
     *     
     */
    public void setAppIteratorLast(AppIteratorUI.AppIteratorLast value) {
        this.appIteratorLast = value;
    }

    /**
     * Gets the value of the appIteratorPrevious property.
     * 
     * @return
     *     possible object is
     *     {@link AppIteratorUI.AppIteratorPrevious }
     *     
     */
    public AppIteratorUI.AppIteratorPrevious getAppIteratorPrevious() {
        return appIteratorPrevious;
    }

    /**
     * Sets the value of the appIteratorPrevious property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppIteratorUI.AppIteratorPrevious }
     *     
     */
    public void setAppIteratorPrevious(AppIteratorUI.AppIteratorPrevious value) {
        this.appIteratorPrevious = value;
    }

    /**
     * Gets the value of the appIteratorNext property.
     * 
     * @return
     *     possible object is
     *     {@link AppIteratorUI.AppIteratorNext }
     *     
     */
    public AppIteratorUI.AppIteratorNext getAppIteratorNext() {
        return appIteratorNext;
    }

    /**
     * Sets the value of the appIteratorNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppIteratorUI.AppIteratorNext }
     *     
     */
    public void setAppIteratorNext(AppIteratorUI.AppIteratorNext value) {
        this.appIteratorNext = value;
    }

    /**
     * Gets the value of the appIteratorLabelArea property.
     * 
     * @return
     *     possible object is
     *     {@link AppIteratorUI.AppIteratorLabelArea }
     *     
     */
    public AppIteratorUI.AppIteratorLabelArea getAppIteratorLabelArea() {
        return appIteratorLabelArea;
    }

    /**
     * Sets the value of the appIteratorLabelArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppIteratorUI.AppIteratorLabelArea }
     *     
     */
    public void setAppIteratorLabelArea(AppIteratorUI.AppIteratorLabelArea value) {
        this.appIteratorLabelArea = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appIteratorButton",
        "appIteratorSiblingLabel",
        "appIteratorSiblingLabelButton",
        "appIteratorText",
        "appIteratorTextButton"
    })
    public static class AppIteratorFirst {

        protected AppIteratorButton appIteratorButton;
        protected AppIteratorSiblingLabel appIteratorSiblingLabel;
        protected AppIteratorSiblingLabelButton appIteratorSiblingLabelButton;
        protected AppIteratorText appIteratorText;
        protected AppIteratorTextButton appIteratorTextButton;

        /**
         * Gets the value of the appIteratorButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorButton }
         *     
         */
        public AppIteratorButton getAppIteratorButton() {
            return appIteratorButton;
        }

        /**
         * Sets the value of the appIteratorButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorButton }
         *     
         */
        public void setAppIteratorButton(AppIteratorButton value) {
            this.appIteratorButton = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabel property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public AppIteratorSiblingLabel getAppIteratorSiblingLabel() {
            return appIteratorSiblingLabel;
        }

        /**
         * Sets the value of the appIteratorSiblingLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public void setAppIteratorSiblingLabel(AppIteratorSiblingLabel value) {
            this.appIteratorSiblingLabel = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabelButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public AppIteratorSiblingLabelButton getAppIteratorSiblingLabelButton() {
            return appIteratorSiblingLabelButton;
        }

        /**
         * Sets the value of the appIteratorSiblingLabelButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public void setAppIteratorSiblingLabelButton(AppIteratorSiblingLabelButton value) {
            this.appIteratorSiblingLabelButton = value;
        }

        /**
         * Gets the value of the appIteratorText property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorText }
         *     
         */
        public AppIteratorText getAppIteratorText() {
            return appIteratorText;
        }

        /**
         * Sets the value of the appIteratorText property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorText }
         *     
         */
        public void setAppIteratorText(AppIteratorText value) {
            this.appIteratorText = value;
        }

        /**
         * Gets the value of the appIteratorTextButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public AppIteratorTextButton getAppIteratorTextButton() {
            return appIteratorTextButton;
        }

        /**
         * Sets the value of the appIteratorTextButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public void setAppIteratorTextButton(AppIteratorTextButton value) {
            this.appIteratorTextButton = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="appIteratorDropDownList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="showIcon" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="width" use="required" type="{http://developer.cognos.com/schemas/report/11.0/}CSSFixedLength" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="appIteratorLabelText">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="textColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="appDotsPageIndicator">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="dotColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" default="gray" />
     *                 &lt;attribute name="activeDotColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" default="white" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="appIteratorNumber">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="textColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" />
     *                 &lt;attribute name="beforeText" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="verticalType" default="number">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="number"/>
     *                       &lt;enumeration value="lowerCaseRoman"/>
     *                       &lt;enumeration value="upperCaseRoman"/>
     *                       &lt;enumeration value="range"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="verticalRangeSeparator" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="afterText" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appIteratorDropDownList",
        "appIteratorLabelText",
        "appDotsPageIndicator",
        "appIteratorNumber"
    })
    public static class AppIteratorLabelArea {

        protected AppIteratorUI.AppIteratorLabelArea.AppIteratorDropDownList appIteratorDropDownList;
        protected AppIteratorUI.AppIteratorLabelArea.AppIteratorLabelText appIteratorLabelText;
        protected AppIteratorUI.AppIteratorLabelArea.AppDotsPageIndicator appDotsPageIndicator;
        protected AppIteratorUI.AppIteratorLabelArea.AppIteratorNumber appIteratorNumber;

        /**
         * Gets the value of the appIteratorDropDownList property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppIteratorDropDownList }
         *     
         */
        public AppIteratorUI.AppIteratorLabelArea.AppIteratorDropDownList getAppIteratorDropDownList() {
            return appIteratorDropDownList;
        }

        /**
         * Sets the value of the appIteratorDropDownList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppIteratorDropDownList }
         *     
         */
        public void setAppIteratorDropDownList(AppIteratorUI.AppIteratorLabelArea.AppIteratorDropDownList value) {
            this.appIteratorDropDownList = value;
        }

        /**
         * Gets the value of the appIteratorLabelText property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppIteratorLabelText }
         *     
         */
        public AppIteratorUI.AppIteratorLabelArea.AppIteratorLabelText getAppIteratorLabelText() {
            return appIteratorLabelText;
        }

        /**
         * Sets the value of the appIteratorLabelText property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppIteratorLabelText }
         *     
         */
        public void setAppIteratorLabelText(AppIteratorUI.AppIteratorLabelArea.AppIteratorLabelText value) {
            this.appIteratorLabelText = value;
        }

        /**
         * Gets the value of the appDotsPageIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppDotsPageIndicator }
         *     
         */
        public AppIteratorUI.AppIteratorLabelArea.AppDotsPageIndicator getAppDotsPageIndicator() {
            return appDotsPageIndicator;
        }

        /**
         * Sets the value of the appDotsPageIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppDotsPageIndicator }
         *     
         */
        public void setAppDotsPageIndicator(AppIteratorUI.AppIteratorLabelArea.AppDotsPageIndicator value) {
            this.appDotsPageIndicator = value;
        }

        /**
         * Gets the value of the appIteratorNumber property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppIteratorNumber }
         *     
         */
        public AppIteratorUI.AppIteratorLabelArea.AppIteratorNumber getAppIteratorNumber() {
            return appIteratorNumber;
        }

        /**
         * Sets the value of the appIteratorNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorUI.AppIteratorLabelArea.AppIteratorNumber }
         *     
         */
        public void setAppIteratorNumber(AppIteratorUI.AppIteratorLabelArea.AppIteratorNumber value) {
            this.appIteratorNumber = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="dotColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" default="gray" />
         *       &lt;attribute name="activeDotColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" default="white" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AppDotsPageIndicator {

            @XmlAttribute(name = "dotColor")
            protected String dotColor;
            @XmlAttribute(name = "activeDotColor")
            protected String activeDotColor;

            /**
             * Gets the value of the dotColor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDotColor() {
                if (dotColor == null) {
                    return "gray";
                } else {
                    return dotColor;
                }
            }

            /**
             * Sets the value of the dotColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDotColor(String value) {
                this.dotColor = value;
            }

            /**
             * Gets the value of the activeDotColor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActiveDotColor() {
                if (activeDotColor == null) {
                    return "white";
                } else {
                    return activeDotColor;
                }
            }

            /**
             * Sets the value of the activeDotColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActiveDotColor(String value) {
                this.activeDotColor = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="showIcon" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="width" use="required" type="{http://developer.cognos.com/schemas/report/11.0/}CSSFixedLength" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AppIteratorDropDownList {

            @XmlAttribute(name = "showIcon")
            protected Boolean showIcon;
            @XmlAttribute(name = "width", required = true)
            protected String width;

            /**
             * Gets the value of the showIcon property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isShowIcon() {
                if (showIcon == null) {
                    return false;
                } else {
                    return showIcon;
                }
            }

            /**
             * Sets the value of the showIcon property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setShowIcon(Boolean value) {
                this.showIcon = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWidth(String value) {
                this.width = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="textColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AppIteratorLabelText {

            @XmlAttribute(name = "textColor")
            protected String textColor;

            /**
             * Gets the value of the textColor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTextColor() {
                return textColor;
            }

            /**
             * Sets the value of the textColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTextColor(String value) {
                this.textColor = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="textColor" type="{http://developer.cognos.com/schemas/report/11.0/}ColorType" />
         *       &lt;attribute name="beforeText" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="verticalType" default="number">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="number"/>
         *             &lt;enumeration value="lowerCaseRoman"/>
         *             &lt;enumeration value="upperCaseRoman"/>
         *             &lt;enumeration value="range"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="verticalRangeSeparator" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="afterText" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AppIteratorNumber {

            @XmlAttribute(name = "textColor")
            protected String textColor;
            @XmlAttribute(name = "beforeText")
            protected String beforeText;
            @XmlAttribute(name = "verticalType")
            protected String verticalType;
            @XmlAttribute(name = "verticalRangeSeparator")
            protected String verticalRangeSeparator;
            @XmlAttribute(name = "afterText")
            protected String afterText;

            /**
             * Gets the value of the textColor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTextColor() {
                return textColor;
            }

            /**
             * Sets the value of the textColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTextColor(String value) {
                this.textColor = value;
            }

            /**
             * Gets the value of the beforeText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBeforeText() {
                return beforeText;
            }

            /**
             * Sets the value of the beforeText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBeforeText(String value) {
                this.beforeText = value;
            }

            /**
             * Gets the value of the verticalType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVerticalType() {
                if (verticalType == null) {
                    return "number";
                } else {
                    return verticalType;
                }
            }

            /**
             * Sets the value of the verticalType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVerticalType(String value) {
                this.verticalType = value;
            }

            /**
             * Gets the value of the verticalRangeSeparator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVerticalRangeSeparator() {
                return verticalRangeSeparator;
            }

            /**
             * Sets the value of the verticalRangeSeparator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVerticalRangeSeparator(String value) {
                this.verticalRangeSeparator = value;
            }

            /**
             * Gets the value of the afterText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAfterText() {
                return afterText;
            }

            /**
             * Sets the value of the afterText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAfterText(String value) {
                this.afterText = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appIteratorButton",
        "appIteratorSiblingLabel",
        "appIteratorSiblingLabelButton",
        "appIteratorText",
        "appIteratorTextButton"
    })
    public static class AppIteratorLast {

        protected AppIteratorButton appIteratorButton;
        protected AppIteratorSiblingLabel appIteratorSiblingLabel;
        protected AppIteratorSiblingLabelButton appIteratorSiblingLabelButton;
        protected AppIteratorText appIteratorText;
        protected AppIteratorTextButton appIteratorTextButton;

        /**
         * Gets the value of the appIteratorButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorButton }
         *     
         */
        public AppIteratorButton getAppIteratorButton() {
            return appIteratorButton;
        }

        /**
         * Sets the value of the appIteratorButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorButton }
         *     
         */
        public void setAppIteratorButton(AppIteratorButton value) {
            this.appIteratorButton = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabel property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public AppIteratorSiblingLabel getAppIteratorSiblingLabel() {
            return appIteratorSiblingLabel;
        }

        /**
         * Sets the value of the appIteratorSiblingLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public void setAppIteratorSiblingLabel(AppIteratorSiblingLabel value) {
            this.appIteratorSiblingLabel = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabelButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public AppIteratorSiblingLabelButton getAppIteratorSiblingLabelButton() {
            return appIteratorSiblingLabelButton;
        }

        /**
         * Sets the value of the appIteratorSiblingLabelButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public void setAppIteratorSiblingLabelButton(AppIteratorSiblingLabelButton value) {
            this.appIteratorSiblingLabelButton = value;
        }

        /**
         * Gets the value of the appIteratorText property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorText }
         *     
         */
        public AppIteratorText getAppIteratorText() {
            return appIteratorText;
        }

        /**
         * Sets the value of the appIteratorText property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorText }
         *     
         */
        public void setAppIteratorText(AppIteratorText value) {
            this.appIteratorText = value;
        }

        /**
         * Gets the value of the appIteratorTextButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public AppIteratorTextButton getAppIteratorTextButton() {
            return appIteratorTextButton;
        }

        /**
         * Sets the value of the appIteratorTextButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public void setAppIteratorTextButton(AppIteratorTextButton value) {
            this.appIteratorTextButton = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appIteratorButton",
        "appIteratorSiblingLabel",
        "appIteratorSiblingLabelButton",
        "appIteratorText",
        "appIteratorTextButton"
    })
    public static class AppIteratorNext {

        protected AppIteratorButton appIteratorButton;
        protected AppIteratorSiblingLabel appIteratorSiblingLabel;
        protected AppIteratorSiblingLabelButton appIteratorSiblingLabelButton;
        protected AppIteratorText appIteratorText;
        protected AppIteratorTextButton appIteratorTextButton;

        /**
         * Gets the value of the appIteratorButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorButton }
         *     
         */
        public AppIteratorButton getAppIteratorButton() {
            return appIteratorButton;
        }

        /**
         * Sets the value of the appIteratorButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorButton }
         *     
         */
        public void setAppIteratorButton(AppIteratorButton value) {
            this.appIteratorButton = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabel property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public AppIteratorSiblingLabel getAppIteratorSiblingLabel() {
            return appIteratorSiblingLabel;
        }

        /**
         * Sets the value of the appIteratorSiblingLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public void setAppIteratorSiblingLabel(AppIteratorSiblingLabel value) {
            this.appIteratorSiblingLabel = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabelButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public AppIteratorSiblingLabelButton getAppIteratorSiblingLabelButton() {
            return appIteratorSiblingLabelButton;
        }

        /**
         * Sets the value of the appIteratorSiblingLabelButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public void setAppIteratorSiblingLabelButton(AppIteratorSiblingLabelButton value) {
            this.appIteratorSiblingLabelButton = value;
        }

        /**
         * Gets the value of the appIteratorText property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorText }
         *     
         */
        public AppIteratorText getAppIteratorText() {
            return appIteratorText;
        }

        /**
         * Sets the value of the appIteratorText property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorText }
         *     
         */
        public void setAppIteratorText(AppIteratorText value) {
            this.appIteratorText = value;
        }

        /**
         * Gets the value of the appIteratorTextButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public AppIteratorTextButton getAppIteratorTextButton() {
            return appIteratorTextButton;
        }

        /**
         * Sets the value of the appIteratorTextButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public void setAppIteratorTextButton(AppIteratorTextButton value) {
            this.appIteratorTextButton = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabel"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorSiblingLabelButton"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorText"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appIteratorTextButton"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appIteratorButton",
        "appIteratorSiblingLabel",
        "appIteratorSiblingLabelButton",
        "appIteratorText",
        "appIteratorTextButton"
    })
    public static class AppIteratorPrevious {

        protected AppIteratorButton appIteratorButton;
        protected AppIteratorSiblingLabel appIteratorSiblingLabel;
        protected AppIteratorSiblingLabelButton appIteratorSiblingLabelButton;
        protected AppIteratorText appIteratorText;
        protected AppIteratorTextButton appIteratorTextButton;

        /**
         * Gets the value of the appIteratorButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorButton }
         *     
         */
        public AppIteratorButton getAppIteratorButton() {
            return appIteratorButton;
        }

        /**
         * Sets the value of the appIteratorButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorButton }
         *     
         */
        public void setAppIteratorButton(AppIteratorButton value) {
            this.appIteratorButton = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabel property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public AppIteratorSiblingLabel getAppIteratorSiblingLabel() {
            return appIteratorSiblingLabel;
        }

        /**
         * Sets the value of the appIteratorSiblingLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabel }
         *     
         */
        public void setAppIteratorSiblingLabel(AppIteratorSiblingLabel value) {
            this.appIteratorSiblingLabel = value;
        }

        /**
         * Gets the value of the appIteratorSiblingLabelButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public AppIteratorSiblingLabelButton getAppIteratorSiblingLabelButton() {
            return appIteratorSiblingLabelButton;
        }

        /**
         * Sets the value of the appIteratorSiblingLabelButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorSiblingLabelButton }
         *     
         */
        public void setAppIteratorSiblingLabelButton(AppIteratorSiblingLabelButton value) {
            this.appIteratorSiblingLabelButton = value;
        }

        /**
         * Gets the value of the appIteratorText property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorText }
         *     
         */
        public AppIteratorText getAppIteratorText() {
            return appIteratorText;
        }

        /**
         * Sets the value of the appIteratorText property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorText }
         *     
         */
        public void setAppIteratorText(AppIteratorText value) {
            this.appIteratorText = value;
        }

        /**
         * Gets the value of the appIteratorTextButton property.
         * 
         * @return
         *     possible object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public AppIteratorTextButton getAppIteratorTextButton() {
            return appIteratorTextButton;
        }

        /**
         * Sets the value of the appIteratorTextButton property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppIteratorTextButton }
         *     
         */
        public void setAppIteratorTextButton(AppIteratorTextButton value) {
            this.appIteratorTextButton = value;
        }

    }

}
