//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="appVariables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="appVariable" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="appVariableValues" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appVariableValue" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                           &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}AppVariableDataTypes"/>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="public" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appWindowTitle" type="{http://developer.cognos.com/schemas/report/11.0/}LocalizedTextType" minOccurs="0"/>
 *         &lt;element name="appWindowIcon" type="{http://developer.cognos.com/schemas/report/11.0/}TextType" minOccurs="0"/>
 *         &lt;element name="appWindowSize" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="appWindowSizeMaximize">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="appWindowSizeFixed">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appMaxRows" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appAccess" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="accessCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="appRanges" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="appRange" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="appRangeMin">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="appRangeMax">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="compressOutput" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="scalable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "appProperties")
public class AppProperties {

    protected AppProperties.AppVariables appVariables;
    protected LocalizedTextType appWindowTitle;
    protected String appWindowIcon;
    protected AppProperties.AppWindowSize appWindowSize;
    protected AppProperties.AppMaxRows appMaxRows;
    protected AppProperties.AppAccess appAccess;
    protected AppProperties.AppRanges appRanges;
    @XmlAttribute(name = "compressOutput")
    protected Boolean compressOutput;
    @XmlAttribute(name = "scalable")
    protected Boolean scalable;

    /**
     * Gets the value of the appVariables property.
     * 
     * @return
     *     possible object is
     *     {@link AppProperties.AppVariables }
     *     
     */
    public AppProperties.AppVariables getAppVariables() {
        return appVariables;
    }

    /**
     * Sets the value of the appVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppProperties.AppVariables }
     *     
     */
    public void setAppVariables(AppProperties.AppVariables value) {
        this.appVariables = value;
    }

    /**
     * Gets the value of the appWindowTitle property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedTextType }
     *     
     */
    public LocalizedTextType getAppWindowTitle() {
        return appWindowTitle;
    }

    /**
     * Sets the value of the appWindowTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedTextType }
     *     
     */
    public void setAppWindowTitle(LocalizedTextType value) {
        this.appWindowTitle = value;
    }

    /**
     * Gets the value of the appWindowIcon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppWindowIcon() {
        return appWindowIcon;
    }

    /**
     * Sets the value of the appWindowIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppWindowIcon(String value) {
        this.appWindowIcon = value;
    }

    /**
     * Gets the value of the appWindowSize property.
     * 
     * @return
     *     possible object is
     *     {@link AppProperties.AppWindowSize }
     *     
     */
    public AppProperties.AppWindowSize getAppWindowSize() {
        return appWindowSize;
    }

    /**
     * Sets the value of the appWindowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppProperties.AppWindowSize }
     *     
     */
    public void setAppWindowSize(AppProperties.AppWindowSize value) {
        this.appWindowSize = value;
    }

    /**
     * Gets the value of the appMaxRows property.
     * 
     * @return
     *     possible object is
     *     {@link AppProperties.AppMaxRows }
     *     
     */
    public AppProperties.AppMaxRows getAppMaxRows() {
        return appMaxRows;
    }

    /**
     * Sets the value of the appMaxRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppProperties.AppMaxRows }
     *     
     */
    public void setAppMaxRows(AppProperties.AppMaxRows value) {
        this.appMaxRows = value;
    }

    /**
     * Gets the value of the appAccess property.
     * 
     * @return
     *     possible object is
     *     {@link AppProperties.AppAccess }
     *     
     */
    public AppProperties.AppAccess getAppAccess() {
        return appAccess;
    }

    /**
     * Sets the value of the appAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppProperties.AppAccess }
     *     
     */
    public void setAppAccess(AppProperties.AppAccess value) {
        this.appAccess = value;
    }

    /**
     * Gets the value of the appRanges property.
     * 
     * @return
     *     possible object is
     *     {@link AppProperties.AppRanges }
     *     
     */
    public AppProperties.AppRanges getAppRanges() {
        return appRanges;
    }

    /**
     * Sets the value of the appRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppProperties.AppRanges }
     *     
     */
    public void setAppRanges(AppProperties.AppRanges value) {
        this.appRanges = value;
    }

    /**
     * Gets the value of the compressOutput property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCompressOutput() {
        if (compressOutput == null) {
            return true;
        } else {
            return compressOutput;
        }
    }

    /**
     * Sets the value of the compressOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompressOutput(Boolean value) {
        this.compressOutput = value;
    }

    /**
     * Gets the value of the scalable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isScalable() {
        if (scalable == null) {
            return true;
        } else {
            return scalable;
        }
    }

    /**
     * Sets the value of the scalable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScalable(Boolean value) {
        this.scalable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="accessCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AppAccess {

        @XmlAttribute(name = "accessCode", required = true)
        protected String accessCode;

        /**
         * Gets the value of the accessCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessCode() {
            return accessCode;
        }

        /**
         * Sets the value of the accessCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessCode(String value) {
            this.accessCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AppMaxRows {

        @XmlAttribute(name = "value", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="appRange" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="appRangeMin">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="appRangeMax">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appRange"
    })
    public static class AppRanges {

        @XmlElement(required = true)
        protected List<AppProperties.AppRanges.AppRange> appRange;

        /**
         * Gets the value of the appRange property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appRange property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppRange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppProperties.AppRanges.AppRange }
         * 
         * 
         */
        public List<AppProperties.AppRanges.AppRange> getAppRange() {
            if (appRange == null) {
                appRange = new ArrayList<AppProperties.AppRanges.AppRange>();
            }
            return this.appRange;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="appRangeMin">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="appRangeMax">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class AppRange {

            @XmlElement(required = true)
            protected AppProperties.AppRanges.AppRange.AppRangeMin appRangeMin;
            @XmlElement(required = true)
            protected AppProperties.AppRanges.AppRange.AppRangeMax appRangeMax;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the appRangeMin property.
             * 
             * @return
             *     possible object is
             *     {@link AppProperties.AppRanges.AppRange.AppRangeMin }
             *     
             */
            public AppProperties.AppRanges.AppRange.AppRangeMin getAppRangeMin() {
                return appRangeMin;
            }

            /**
             * Sets the value of the appRangeMin property.
             * 
             * @param value
             *     allowed object is
             *     {@link AppProperties.AppRanges.AppRange.AppRangeMin }
             *     
             */
            public void setAppRangeMin(AppProperties.AppRanges.AppRange.AppRangeMin value) {
                this.appRangeMin = value;
            }

            /**
             * Gets the value of the appRangeMax property.
             * 
             * @return
             *     possible object is
             *     {@link AppProperties.AppRanges.AppRange.AppRangeMax }
             *     
             */
            public AppProperties.AppRanges.AppRange.AppRangeMax getAppRangeMax() {
                return appRangeMax;
            }

            /**
             * Sets the value of the appRangeMax property.
             * 
             * @param value
             *     allowed object is
             *     {@link AppProperties.AppRanges.AppRange.AppRangeMax }
             *     
             */
            public void setAppRangeMax(AppProperties.AppRanges.AppRange.AppRangeMax value) {
                this.appRangeMax = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class AppRangeMax {

                @XmlAttribute(name = "refAppVariable", required = true)
                protected String refAppVariable;

                /**
                 * Gets the value of the refAppVariable property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRefAppVariable() {
                    return refAppVariable;
                }

                /**
                 * Sets the value of the refAppVariable property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRefAppVariable(String value) {
                    this.refAppVariable = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="refAppVariable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class AppRangeMin {

                @XmlAttribute(name = "refAppVariable", required = true)
                protected String refAppVariable;

                /**
                 * Gets the value of the refAppVariable property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRefAppVariable() {
                    return refAppVariable;
                }

                /**
                 * Sets the value of the refAppVariable property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRefAppVariable(String value) {
                    this.refAppVariable = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="appVariable" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="appVariableValues" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appVariableValue" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *                 &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}AppVariableDataTypes"/>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="public" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appVariable"
    })
    public static class AppVariables {

        @XmlElement(required = true)
        protected List<AppProperties.AppVariables.AppVariable> appVariable;

        /**
         * Gets the value of the appVariable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appVariable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppVariable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppProperties.AppVariables.AppVariable }
         * 
         * 
         */
        public List<AppProperties.AppVariables.AppVariable> getAppVariable() {
            if (appVariable == null) {
                appVariable = new ArrayList<AppProperties.AppVariables.AppVariable>();
            }
            return this.appVariable;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="appVariableValues" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appVariableValue" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *       &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}AppVariableDataTypes"/>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="public" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class AppVariable {

            protected AppProperties.AppVariables.AppVariable.AppVariableValues appVariableValues;
            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "public")
            protected Boolean _public;
            @XmlAttribute(name = "dataType")
            protected String dataType;

            /**
             * Gets the value of the appVariableValues property.
             * 
             * @return
             *     possible object is
             *     {@link AppProperties.AppVariables.AppVariable.AppVariableValues }
             *     
             */
            public AppProperties.AppVariables.AppVariable.AppVariableValues getAppVariableValues() {
                return appVariableValues;
            }

            /**
             * Sets the value of the appVariableValues property.
             * 
             * @param value
             *     allowed object is
             *     {@link AppProperties.AppVariables.AppVariable.AppVariableValues }
             *     
             */
            public void setAppVariableValues(AppProperties.AppVariables.AppVariable.AppVariableValues value) {
                this.appVariableValues = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the public property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isPublic() {
                if (_public == null) {
                    return false;
                } else {
                    return _public;
                }
            }

            /**
             * Sets the value of the public property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPublic(Boolean value) {
                this._public = value;
            }

            /**
             * Gets the value of the dataType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataType() {
                if (dataType == null) {
                    return "string";
                } else {
                    return dataType;
                }
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataType(String value) {
                this.dataType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appVariableValue" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "appVariableValue"
            })
            public static class AppVariableValues {

                @XmlElement(required = true)
                protected List<AppVariableValue> appVariableValue;

                /**
                 * Gets the value of the appVariableValue property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the appVariableValue property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAppVariableValue().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link AppVariableValue }
                 * 
                 * 
                 */
                public List<AppVariableValue> getAppVariableValue() {
                    if (appVariableValue == null) {
                        appVariableValue = new ArrayList<AppVariableValue>();
                    }
                    return this.appVariableValue;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="appWindowSizeMaximize">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="appWindowSizeFixed">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appWindowSizeMaximize",
        "appWindowSizeFixed"
    })
    public static class AppWindowSize {

        protected AppProperties.AppWindowSize.AppWindowSizeMaximize appWindowSizeMaximize;
        protected AppProperties.AppWindowSize.AppWindowSizeFixed appWindowSizeFixed;

        /**
         * Gets the value of the appWindowSizeMaximize property.
         * 
         * @return
         *     possible object is
         *     {@link AppProperties.AppWindowSize.AppWindowSizeMaximize }
         *     
         */
        public AppProperties.AppWindowSize.AppWindowSizeMaximize getAppWindowSizeMaximize() {
            return appWindowSizeMaximize;
        }

        /**
         * Sets the value of the appWindowSizeMaximize property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppProperties.AppWindowSize.AppWindowSizeMaximize }
         *     
         */
        public void setAppWindowSizeMaximize(AppProperties.AppWindowSize.AppWindowSizeMaximize value) {
            this.appWindowSizeMaximize = value;
        }

        /**
         * Gets the value of the appWindowSizeFixed property.
         * 
         * @return
         *     possible object is
         *     {@link AppProperties.AppWindowSize.AppWindowSizeFixed }
         *     
         */
        public AppProperties.AppWindowSize.AppWindowSizeFixed getAppWindowSizeFixed() {
            return appWindowSizeFixed;
        }

        /**
         * Sets the value of the appWindowSizeFixed property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppProperties.AppWindowSize.AppWindowSizeFixed }
         *     
         */
        public void setAppWindowSizeFixed(AppProperties.AppWindowSize.AppWindowSizeFixed value) {
            this.appWindowSizeFixed = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AppWindowSizeFixed {

            @XmlAttribute(name = "width", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger width;
            @XmlAttribute(name = "height", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger height;

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setWidth(BigInteger value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setHeight(BigInteger value) {
                this.height = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AppWindowSizeMaximize {


        }

    }

}
