//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}appStaticDataItems"/>
 *         &lt;element name="appStaticDataRows">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="appStaticDataRow" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="appStaticDataItemValue" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{http://developer.cognos.com/schemas/report/11.0/}LocalizedTextType">
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "appStaticDataTable")
public class AppStaticDataTable {

    @XmlElement(required = true)
    protected AppStaticDataItems appStaticDataItems;
    @XmlElement(required = true)
    protected AppStaticDataTable.AppStaticDataRows appStaticDataRows;

    /**
     * Represents the data items that will have values for each row (e.g. list item) of the control. The order of the data items represents the order they will appear in the data rows.
     * 
     * @return
     *     possible object is
     *     {@link AppStaticDataItems }
     *     
     */
    public AppStaticDataItems getAppStaticDataItems() {
        return appStaticDataItems;
    }

    /**
     * Sets the value of the appStaticDataItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppStaticDataItems }
     *     
     */
    public void setAppStaticDataItems(AppStaticDataItems value) {
        this.appStaticDataItems = value;
    }

    /**
     * Gets the value of the appStaticDataRows property.
     * 
     * @return
     *     possible object is
     *     {@link AppStaticDataTable.AppStaticDataRows }
     *     
     */
    public AppStaticDataTable.AppStaticDataRows getAppStaticDataRows() {
        return appStaticDataRows;
    }

    /**
     * Sets the value of the appStaticDataRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppStaticDataTable.AppStaticDataRows }
     *     
     */
    public void setAppStaticDataRows(AppStaticDataTable.AppStaticDataRows value) {
        this.appStaticDataRows = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="appStaticDataRow" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="appStaticDataItemValue" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://developer.cognos.com/schemas/report/11.0/}LocalizedTextType">
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appStaticDataRow"
    })
    public static class AppStaticDataRows {

        @XmlElement(required = true)
        protected List<AppStaticDataTable.AppStaticDataRows.AppStaticDataRow> appStaticDataRow;

        /**
         * Gets the value of the appStaticDataRow property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the appStaticDataRow property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAppStaticDataRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppStaticDataTable.AppStaticDataRows.AppStaticDataRow }
         * 
         * 
         */
        public List<AppStaticDataTable.AppStaticDataRows.AppStaticDataRow> getAppStaticDataRow() {
            if (appStaticDataRow == null) {
                appStaticDataRow = new ArrayList<AppStaticDataTable.AppStaticDataRows.AppStaticDataRow>();
            }
            return this.appStaticDataRow;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="appStaticDataItemValue" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://developer.cognos.com/schemas/report/11.0/}LocalizedTextType">
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "appStaticDataItemValue"
        })
        public static class AppStaticDataRow {

            @XmlElement(required = true)
            protected List<AppStaticDataTable.AppStaticDataRows.AppStaticDataRow.AppStaticDataItemValue> appStaticDataItemValue;

            /**
             * Gets the value of the appStaticDataItemValue property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the appStaticDataItemValue property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAppStaticDataItemValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AppStaticDataTable.AppStaticDataRows.AppStaticDataRow.AppStaticDataItemValue }
             * 
             * 
             */
            public List<AppStaticDataTable.AppStaticDataRows.AppStaticDataRow.AppStaticDataItemValue> getAppStaticDataItemValue() {
                if (appStaticDataItemValue == null) {
                    appStaticDataItemValue = new ArrayList<AppStaticDataTable.AppStaticDataRows.AppStaticDataRow.AppStaticDataItemValue>();
                }
                return this.appStaticDataItemValue;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://developer.cognos.com/schemas/report/11.0/}LocalizedTextType">
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class AppStaticDataItemValue
                extends LocalizedTextType
            {


            }

        }

    }

}
