//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="burstGroups">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="burstGroup" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}sortList" minOccurs="0"/>
 *                           &lt;/all>
 *                           &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="burstRecipient">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}masterDetailLinks" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="refQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" default="auto">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="auto"/>
 *                       &lt;enumeration value="email"/>
 *                       &lt;enumeration value="directory"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="burstLabel" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="refQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "burst")
public class Burst {

    @XmlElement(required = true)
    protected Burst.BurstGroups burstGroups;
    @XmlElement(required = true)
    protected Burst.BurstRecipient burstRecipient;
    protected Burst.BurstLabel burstLabel;
    @XmlAttribute(name = "refQuery", required = true)
    protected String refQuery;

    /**
     * Gets the value of the burstGroups property.
     * 
     * @return
     *     possible object is
     *     {@link Burst.BurstGroups }
     *     
     */
    public Burst.BurstGroups getBurstGroups() {
        return burstGroups;
    }

    /**
     * Sets the value of the burstGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Burst.BurstGroups }
     *     
     */
    public void setBurstGroups(Burst.BurstGroups value) {
        this.burstGroups = value;
    }

    /**
     * Gets the value of the burstRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link Burst.BurstRecipient }
     *     
     */
    public Burst.BurstRecipient getBurstRecipient() {
        return burstRecipient;
    }

    /**
     * Sets the value of the burstRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Burst.BurstRecipient }
     *     
     */
    public void setBurstRecipient(Burst.BurstRecipient value) {
        this.burstRecipient = value;
    }

    /**
     * Gets the value of the burstLabel property.
     * 
     * @return
     *     possible object is
     *     {@link Burst.BurstLabel }
     *     
     */
    public Burst.BurstLabel getBurstLabel() {
        return burstLabel;
    }

    /**
     * Sets the value of the burstLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Burst.BurstLabel }
     *     
     */
    public void setBurstLabel(Burst.BurstLabel value) {
        this.burstLabel = value;
    }

    /**
     * Gets the value of the refQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefQuery() {
        return refQuery;
    }

    /**
     * Sets the value of the refQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefQuery(String value) {
        this.refQuery = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="burstGroup" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}sortList" minOccurs="0"/>
     *                 &lt;/all>
     *                 &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "burstGroup"
    })
    public static class BurstGroups {

        @XmlElement(required = true)
        protected List<Burst.BurstGroups.BurstGroup> burstGroup;

        /**
         * Gets the value of the burstGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the burstGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBurstGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Burst.BurstGroups.BurstGroup }
         * 
         * 
         */
        public List<Burst.BurstGroups.BurstGroup> getBurstGroup() {
            if (burstGroup == null) {
                burstGroup = new ArrayList<Burst.BurstGroups.BurstGroup>();
            }
            return this.burstGroup;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}sortList" minOccurs="0"/>
         *       &lt;/all>
         *       &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class BurstGroup {

            protected SortList sortList;
            @XmlAttribute(name = "refDataItem", required = true)
            protected String refDataItem;

            /**
             * Gets the value of the sortList property.
             * 
             * @return
             *     possible object is
             *     {@link SortList }
             *     
             */
            public SortList getSortList() {
                return sortList;
            }

            /**
             * Sets the value of the sortList property.
             * 
             * @param value
             *     allowed object is
             *     {@link SortList }
             *     
             */
            public void setSortList(SortList value) {
                this.sortList = value;
            }

            /**
             * Gets the value of the refDataItem property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefDataItem() {
                return refDataItem;
            }

            /**
             * Sets the value of the refDataItem property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefDataItem(String value) {
                this.refDataItem = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BurstLabel {

        @XmlAttribute(name = "refDataItem", required = true)
        protected String refDataItem;

        /**
         * Gets the value of the refDataItem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefDataItem() {
            return refDataItem;
        }

        /**
         * Sets the value of the refDataItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefDataItem(String value) {
            this.refDataItem = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}masterDetailLinks" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="refQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="refDataItem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type" default="auto">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="auto"/>
     *             &lt;enumeration value="email"/>
     *             &lt;enumeration value="directory"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class BurstRecipient {

        protected MasterDetailLinks masterDetailLinks;
        @XmlAttribute(name = "refQuery", required = true)
        protected String refQuery;
        @XmlAttribute(name = "refDataItem", required = true)
        protected String refDataItem;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the masterDetailLinks property.
         * 
         * @return
         *     possible object is
         *     {@link MasterDetailLinks }
         *     
         */
        public MasterDetailLinks getMasterDetailLinks() {
            return masterDetailLinks;
        }

        /**
         * Sets the value of the masterDetailLinks property.
         * 
         * @param value
         *     allowed object is
         *     {@link MasterDetailLinks }
         *     
         */
        public void setMasterDetailLinks(MasterDetailLinks value) {
            this.masterDetailLinks = value;
        }

        /**
         * Gets the value of the refQuery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefQuery() {
            return refQuery;
        }

        /**
         * Sets the value of the refQuery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefQuery(String value) {
            this.refQuery = value;
        }

        /**
         * Gets the value of the refDataItem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefDataItem() {
            return refDataItem;
        }

        /**
         * Sets the value of the refDataItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefDataItem(String value) {
            this.refDataItem = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            if (type == null) {
                return "auto";
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
