//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conditionalChartColor" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}chartColor"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}chartGradient"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}chartPattern"/>
 *                 &lt;/choice>
 *                 &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}ConditionalPartAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}ConditionalOwnerAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conditionalChartColor"
})
@XmlRootElement(name = "conditionalChartColors")
public class ConditionalChartColors {

    @XmlElement(required = true)
    protected List<ConditionalChartColors.ConditionalChartColor> conditionalChartColor;
    @XmlAttribute(name = "refVariable", required = true)
    protected String refVariable;

    /**
     * Gets the value of the conditionalChartColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionalChartColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionalChartColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionalChartColors.ConditionalChartColor }
     * 
     * 
     */
    public List<ConditionalChartColors.ConditionalChartColor> getConditionalChartColor() {
        if (conditionalChartColor == null) {
            conditionalChartColor = new ArrayList<ConditionalChartColors.ConditionalChartColor>();
        }
        return this.conditionalChartColor;
    }

    /**
     * Gets the value of the refVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefVariable() {
        return refVariable;
    }

    /**
     * Sets the value of the refVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefVariable(String value) {
        this.refVariable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}chartColor"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}chartGradient"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}chartPattern"/>
     *       &lt;/choice>
     *       &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}ConditionalPartAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chartColor",
        "chartGradient",
        "chartPattern"
    })
    public static class ConditionalChartColor {

        protected ChartColor chartColor;
        protected ChartGradient chartGradient;
        protected ChartPattern chartPattern;
        @XmlAttribute(name = "refVariableValue", required = true)
        protected String refVariableValue;

        /**
         * Gets the value of the chartColor property.
         * 
         * @return
         *     possible object is
         *     {@link ChartColor }
         *     
         */
        public ChartColor getChartColor() {
            return chartColor;
        }

        /**
         * Sets the value of the chartColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link ChartColor }
         *     
         */
        public void setChartColor(ChartColor value) {
            this.chartColor = value;
        }

        /**
         * Gets the value of the chartGradient property.
         * 
         * @return
         *     possible object is
         *     {@link ChartGradient }
         *     
         */
        public ChartGradient getChartGradient() {
            return chartGradient;
        }

        /**
         * Sets the value of the chartGradient property.
         * 
         * @param value
         *     allowed object is
         *     {@link ChartGradient }
         *     
         */
        public void setChartGradient(ChartGradient value) {
            this.chartGradient = value;
        }

        /**
         * Gets the value of the chartPattern property.
         * 
         * @return
         *     possible object is
         *     {@link ChartPattern }
         *     
         */
        public ChartPattern getChartPattern() {
            return chartPattern;
        }

        /**
         * Sets the value of the chartPattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link ChartPattern }
         *     
         */
        public void setChartPattern(ChartPattern value) {
            this.chartPattern = value;
        }

        /**
         * Gets the value of the refVariableValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefVariableValue() {
            return refVariableValue;
        }

        /**
         * Sets the value of the refVariableValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefVariableValue(String value) {
            this.refVariableValue = value;
        }

    }

}
