//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="advancedConditionalStyle">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;all>
 *                     &lt;element name="styleCases" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="styleCase" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;all>
 *                                         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}reportCondition"/>
 *                                         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
 *                                       &lt;/all>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleDefault" minOccurs="0"/>
 *                   &lt;/all>
 *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="rangeConditionalStyle">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;all>
 *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}conditionalDataItem"/>
 *                     &lt;element name="styleRanges" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="styleRange" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;all>
 *                                         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
 *                                       &lt;/all>
 *                                       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                       &lt;attribute name="inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="styleRangeRemaining" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;all>
 *                               &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
 *                             &lt;/all>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleDefault" minOccurs="0"/>
 *                   &lt;/all>
 *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="type" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         &lt;enumeration value="number"/>
 *                         &lt;enumeration value="date"/>
 *                         &lt;enumeration value="dateTime"/>
 *                         &lt;enumeration value="time"/>
 *                         &lt;enumeration value="interval"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="stringsConditionalStyle">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;all>
 *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}conditionalDataItem"/>
 *                     &lt;element name="stringConditions" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice maxOccurs="unbounded">
 *                                 &lt;element name="stringValueList">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;all>
 *                                           &lt;element name="styleValues">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue" maxOccurs="unbounded"/>
 *                                                   &lt;/sequence>
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                           &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
 *                                         &lt;/all>
 *                                         &lt;attribute name="selectedValues" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                                 &lt;element name="stringCriteria">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;all>
 *                                           &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue"/>
 *                                           &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
 *                                         &lt;/all>
 *                                         &lt;attribute name="operator" use="required">
 *                                           &lt;simpleType>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                               &lt;enumeration value="contains"/>
 *                                               &lt;enumeration value="like"/>
 *                                               &lt;enumeration value="beginsWith"/>
 *                                               &lt;enumeration value="endsWith"/>
 *                                               &lt;enumeration value="notContains"/>
 *                                               &lt;enumeration value="notLike"/>
 *                                               &lt;enumeration value="notEndsWith"/>
 *                                               &lt;enumeration value="notBeginsWith"/>
 *                                             &lt;/restriction>
 *                                           &lt;/simpleType>
 *                                         &lt;/attribute>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/choice>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleDefault" minOccurs="0"/>
 *                   &lt;/all>
 *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle"
})
@XmlRootElement(name = "namedConditionalStyles")
public class NamedConditionalStyles {

    @XmlElements({
        @XmlElement(name = "advancedConditionalStyle", type = NamedConditionalStyles.AdvancedConditionalStyle.class),
        @XmlElement(name = "rangeConditionalStyle", type = NamedConditionalStyles.RangeConditionalStyle.class),
        @XmlElement(name = "stringsConditionalStyle", type = NamedConditionalStyles.StringsConditionalStyle.class)
    })
    protected List<Object> advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle;

    /**
     * Gets the value of the advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdvancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NamedConditionalStyles.AdvancedConditionalStyle }
     * {@link NamedConditionalStyles.RangeConditionalStyle }
     * {@link NamedConditionalStyles.StringsConditionalStyle }
     * 
     * 
     */
    public List<Object> getAdvancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle() {
        if (advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle == null) {
            advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle = new ArrayList<Object>();
        }
        return this.advancedConditionalStyleOrRangeConditionalStyleOrStringsConditionalStyle;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="styleCases" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="styleCase" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}reportCondition"/>
     *                             &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleDefault" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class AdvancedConditionalStyle {

        protected NamedConditionalStyles.AdvancedConditionalStyle.StyleCases styleCases;
        protected StyleDefault styleDefault;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the styleCases property.
         * 
         * @return
         *     possible object is
         *     {@link NamedConditionalStyles.AdvancedConditionalStyle.StyleCases }
         *     
         */
        public NamedConditionalStyles.AdvancedConditionalStyle.StyleCases getStyleCases() {
            return styleCases;
        }

        /**
         * Sets the value of the styleCases property.
         * 
         * @param value
         *     allowed object is
         *     {@link NamedConditionalStyles.AdvancedConditionalStyle.StyleCases }
         *     
         */
        public void setStyleCases(NamedConditionalStyles.AdvancedConditionalStyle.StyleCases value) {
            this.styleCases = value;
        }

        /**
         * Gets the value of the styleDefault property.
         * 
         * @return
         *     possible object is
         *     {@link StyleDefault }
         *     
         */
        public StyleDefault getStyleDefault() {
            return styleDefault;
        }

        /**
         * Sets the value of the styleDefault property.
         * 
         * @param value
         *     allowed object is
         *     {@link StyleDefault }
         *     
         */
        public void setStyleDefault(StyleDefault value) {
            this.styleDefault = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="styleCase" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}reportCondition"/>
         *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "styleCase"
        })
        public static class StyleCases {

            @XmlElement(required = true)
            protected List<NamedConditionalStyles.AdvancedConditionalStyle.StyleCases.StyleCase> styleCase;

            /**
             * Gets the value of the styleCase property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the styleCase property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStyleCase().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NamedConditionalStyles.AdvancedConditionalStyle.StyleCases.StyleCase }
             * 
             * 
             */
            public List<NamedConditionalStyles.AdvancedConditionalStyle.StyleCases.StyleCase> getStyleCase() {
                if (styleCase == null) {
                    styleCase = new ArrayList<NamedConditionalStyles.AdvancedConditionalStyle.StyleCases.StyleCase>();
                }
                return this.styleCase;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}reportCondition"/>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class StyleCase {

                @XmlElement(required = true)
                protected String reportCondition;
                protected Style style;

                /**
                 * Gets the value of the reportCondition property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReportCondition() {
                    return reportCondition;
                }

                /**
                 * Sets the value of the reportCondition property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReportCondition(String value) {
                    this.reportCondition = value;
                }

                /**
                 * Gets the value of the style property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Style }
                 *     
                 */
                public Style getStyle() {
                    return style;
                }

                /**
                 * Sets the value of the style property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Style }
                 *     
                 */
                public void setStyle(Style value) {
                    this.style = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}conditionalDataItem"/>
     *         &lt;element name="styleRanges" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="styleRange" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
     *                           &lt;/all>
     *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="styleRangeRemaining" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleDefault" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="number"/>
     *             &lt;enumeration value="date"/>
     *             &lt;enumeration value="dateTime"/>
     *             &lt;enumeration value="time"/>
     *             &lt;enumeration value="interval"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class RangeConditionalStyle {

        @XmlElement(required = true)
        protected ConditionalDataItem conditionalDataItem;
        protected NamedConditionalStyles.RangeConditionalStyle.StyleRanges styleRanges;
        protected NamedConditionalStyles.RangeConditionalStyle.StyleRangeRemaining styleRangeRemaining;
        protected StyleDefault styleDefault;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "type", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String type;

        /**
         * Gets the value of the conditionalDataItem property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionalDataItem }
         *     
         */
        public ConditionalDataItem getConditionalDataItem() {
            return conditionalDataItem;
        }

        /**
         * Sets the value of the conditionalDataItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionalDataItem }
         *     
         */
        public void setConditionalDataItem(ConditionalDataItem value) {
            this.conditionalDataItem = value;
        }

        /**
         * Gets the value of the styleRanges property.
         * 
         * @return
         *     possible object is
         *     {@link NamedConditionalStyles.RangeConditionalStyle.StyleRanges }
         *     
         */
        public NamedConditionalStyles.RangeConditionalStyle.StyleRanges getStyleRanges() {
            return styleRanges;
        }

        /**
         * Sets the value of the styleRanges property.
         * 
         * @param value
         *     allowed object is
         *     {@link NamedConditionalStyles.RangeConditionalStyle.StyleRanges }
         *     
         */
        public void setStyleRanges(NamedConditionalStyles.RangeConditionalStyle.StyleRanges value) {
            this.styleRanges = value;
        }

        /**
         * Gets the value of the styleRangeRemaining property.
         * 
         * @return
         *     possible object is
         *     {@link NamedConditionalStyles.RangeConditionalStyle.StyleRangeRemaining }
         *     
         */
        public NamedConditionalStyles.RangeConditionalStyle.StyleRangeRemaining getStyleRangeRemaining() {
            return styleRangeRemaining;
        }

        /**
         * Sets the value of the styleRangeRemaining property.
         * 
         * @param value
         *     allowed object is
         *     {@link NamedConditionalStyles.RangeConditionalStyle.StyleRangeRemaining }
         *     
         */
        public void setStyleRangeRemaining(NamedConditionalStyles.RangeConditionalStyle.StyleRangeRemaining value) {
            this.styleRangeRemaining = value;
        }

        /**
         * Gets the value of the styleDefault property.
         * 
         * @return
         *     possible object is
         *     {@link StyleDefault }
         *     
         */
        public StyleDefault getStyleDefault() {
            return styleDefault;
        }

        /**
         * Sets the value of the styleDefault property.
         * 
         * @param value
         *     allowed object is
         *     {@link StyleDefault }
         *     
         */
        public void setStyleDefault(StyleDefault value) {
            this.styleDefault = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class StyleRangeRemaining {

            protected Style style;

            /**
             * Gets the value of the style property.
             * 
             * @return
             *     possible object is
             *     {@link Style }
             *     
             */
            public Style getStyle() {
                return style;
            }

            /**
             * Sets the value of the style property.
             * 
             * @param value
             *     allowed object is
             *     {@link Style }
             *     
             */
            public void setStyle(Style value) {
                this.style = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="styleRange" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
         *                 &lt;/all>
         *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "styleRange"
        })
        public static class StyleRanges {

            @XmlElement(required = true)
            protected List<NamedConditionalStyles.RangeConditionalStyle.StyleRanges.StyleRange> styleRange;

            /**
             * Gets the value of the styleRange property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the styleRange property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStyleRange().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NamedConditionalStyles.RangeConditionalStyle.StyleRanges.StyleRange }
             * 
             * 
             */
            public List<NamedConditionalStyles.RangeConditionalStyle.StyleRanges.StyleRange> getStyleRange() {
                if (styleRange == null) {
                    styleRange = new ArrayList<NamedConditionalStyles.RangeConditionalStyle.StyleRanges.StyleRange>();
                }
                return this.styleRange;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
             *       &lt;/all>
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="inclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class StyleRange {

                protected Style style;
                @XmlAttribute(name = "value", required = true)
                protected String value;
                @XmlAttribute(name = "inclusive")
                protected Boolean inclusive;

                /**
                 * Gets the value of the style property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Style }
                 *     
                 */
                public Style getStyle() {
                    return style;
                }

                /**
                 * Sets the value of the style property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Style }
                 *     
                 */
                public void setStyle(Style value) {
                    this.style = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the inclusive property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isInclusive() {
                    if (inclusive == null) {
                        return false;
                    } else {
                        return inclusive;
                    }
                }

                /**
                 * Sets the value of the inclusive property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setInclusive(Boolean value) {
                    this.inclusive = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}conditionalDataItem"/>
     *         &lt;element name="stringConditions" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice maxOccurs="unbounded">
     *                     &lt;element name="stringValueList">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;all>
     *                               &lt;element name="styleValues">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue" maxOccurs="unbounded"/>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
     *                             &lt;/all>
     *                             &lt;attribute name="selectedValues" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="stringCriteria">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;all>
     *                               &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue"/>
     *                               &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
     *                             &lt;/all>
     *                             &lt;attribute name="operator" use="required">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="contains"/>
     *                                   &lt;enumeration value="like"/>
     *                                   &lt;enumeration value="beginsWith"/>
     *                                   &lt;enumeration value="endsWith"/>
     *                                   &lt;enumeration value="notContains"/>
     *                                   &lt;enumeration value="notLike"/>
     *                                   &lt;enumeration value="notEndsWith"/>
     *                                   &lt;enumeration value="notBeginsWith"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/attribute>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleDefault" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class StringsConditionalStyle {

        @XmlElement(required = true)
        protected ConditionalDataItem conditionalDataItem;
        protected NamedConditionalStyles.StringsConditionalStyle.StringConditions stringConditions;
        protected StyleDefault styleDefault;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the conditionalDataItem property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionalDataItem }
         *     
         */
        public ConditionalDataItem getConditionalDataItem() {
            return conditionalDataItem;
        }

        /**
         * Sets the value of the conditionalDataItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionalDataItem }
         *     
         */
        public void setConditionalDataItem(ConditionalDataItem value) {
            this.conditionalDataItem = value;
        }

        /**
         * Gets the value of the stringConditions property.
         * 
         * @return
         *     possible object is
         *     {@link NamedConditionalStyles.StringsConditionalStyle.StringConditions }
         *     
         */
        public NamedConditionalStyles.StringsConditionalStyle.StringConditions getStringConditions() {
            return stringConditions;
        }

        /**
         * Sets the value of the stringConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link NamedConditionalStyles.StringsConditionalStyle.StringConditions }
         *     
         */
        public void setStringConditions(NamedConditionalStyles.StringsConditionalStyle.StringConditions value) {
            this.stringConditions = value;
        }

        /**
         * Gets the value of the styleDefault property.
         * 
         * @return
         *     possible object is
         *     {@link StyleDefault }
         *     
         */
        public StyleDefault getStyleDefault() {
            return styleDefault;
        }

        /**
         * Sets the value of the styleDefault property.
         * 
         * @param value
         *     allowed object is
         *     {@link StyleDefault }
         *     
         */
        public void setStyleDefault(StyleDefault value) {
            this.styleDefault = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice maxOccurs="unbounded">
         *           &lt;element name="stringValueList">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;all>
         *                     &lt;element name="styleValues">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue" maxOccurs="unbounded"/>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
         *                   &lt;/all>
         *                   &lt;attribute name="selectedValues" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="stringCriteria">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;all>
         *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue"/>
         *                     &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
         *                   &lt;/all>
         *                   &lt;attribute name="operator" use="required">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="contains"/>
         *                         &lt;enumeration value="like"/>
         *                         &lt;enumeration value="beginsWith"/>
         *                         &lt;enumeration value="endsWith"/>
         *                         &lt;enumeration value="notContains"/>
         *                         &lt;enumeration value="notLike"/>
         *                         &lt;enumeration value="notEndsWith"/>
         *                         &lt;enumeration value="notBeginsWith"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/attribute>
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stringValueListOrStringCriteria"
        })
        public static class StringConditions {

            @XmlElements({
                @XmlElement(name = "stringValueList", type = NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList.class),
                @XmlElement(name = "stringCriteria", type = NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringCriteria.class)
            })
            protected List<Object> stringValueListOrStringCriteria;

            /**
             * Gets the value of the stringValueListOrStringCriteria property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stringValueListOrStringCriteria property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStringValueListOrStringCriteria().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList }
             * {@link NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringCriteria }
             * 
             * 
             */
            public List<Object> getStringValueListOrStringCriteria() {
                if (stringValueListOrStringCriteria == null) {
                    stringValueListOrStringCriteria = new ArrayList<Object>();
                }
                return this.stringValueListOrStringCriteria;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue"/>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
             *       &lt;/all>
             *       &lt;attribute name="operator" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="contains"/>
             *             &lt;enumeration value="like"/>
             *             &lt;enumeration value="beginsWith"/>
             *             &lt;enumeration value="endsWith"/>
             *             &lt;enumeration value="notContains"/>
             *             &lt;enumeration value="notLike"/>
             *             &lt;enumeration value="notEndsWith"/>
             *             &lt;enumeration value="notBeginsWith"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class StringCriteria {

                @XmlElement(required = true)
                protected String styleValue;
                protected Style style;
                @XmlAttribute(name = "operator", required = true)
                protected String operator;

                /**
                 * Gets the value of the styleValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStyleValue() {
                    return styleValue;
                }

                /**
                 * Sets the value of the styleValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStyleValue(String value) {
                    this.styleValue = value;
                }

                /**
                 * Gets the value of the style property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Style }
                 *     
                 */
                public Style getStyle() {
                    return style;
                }

                /**
                 * Sets the value of the style property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Style }
                 *     
                 */
                public void setStyle(Style value) {
                    this.style = value;
                }

                /**
                 * Gets the value of the operator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOperator() {
                    return operator;
                }

                /**
                 * Sets the value of the operator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOperator(String value) {
                    this.operator = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="styleValues">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}style" minOccurs="0"/>
             *       &lt;/all>
             *       &lt;attribute name="selectedValues" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class StringValueList {

                @XmlElement(required = true)
                protected NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList.StyleValues styleValues;
                protected Style style;
                @XmlAttribute(name = "selectedValues")
                protected Boolean selectedValues;

                /**
                 * Gets the value of the styleValues property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList.StyleValues }
                 *     
                 */
                public NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList.StyleValues getStyleValues() {
                    return styleValues;
                }

                /**
                 * Sets the value of the styleValues property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList.StyleValues }
                 *     
                 */
                public void setStyleValues(NamedConditionalStyles.StringsConditionalStyle.StringConditions.StringValueList.StyleValues value) {
                    this.styleValues = value;
                }

                /**
                 * Gets the value of the style property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Style }
                 *     
                 */
                public Style getStyle() {
                    return style;
                }

                /**
                 * Sets the value of the style property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Style }
                 *     
                 */
                public void setStyle(Style value) {
                    this.style = value;
                }

                /**
                 * Gets the value of the selectedValues property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isSelectedValues() {
                    if (selectedValues == null) {
                        return true;
                    } else {
                        return selectedValues;
                    }
                }

                /**
                 * Sets the value of the selectedValues property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setSelectedValues(Boolean value) {
                    this.selectedValues = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}styleValue" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "styleValue"
                })
                public static class StyleValues {

                    @XmlElement(required = true)
                    protected List<String> styleValue;

                    /**
                     * Gets the value of the styleValue property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the styleValue property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getStyleValue().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getStyleValue() {
                        if (styleValue == null) {
                            styleValue = new ArrayList<String>();
                        }
                        return this.styleValue;
                    }

                }

            }

        }

    }

}
