//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * TODO: This is incomplete.  Missing label position control.  The number of minor intervals controls how many minor gridlines or tick marks are rendered.  This allows you to have either minor gridlines, minor tick marks or both.
 * 
 * <p>Java class for OrdinalAxis2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrdinalAxis2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_axisTitle" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}reportDrills" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_axisLabels" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_axisLine" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_majorGridlines" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_minorGridlines" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_majorBackgroundColors" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}XMLAttributes" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}AxisAttributes2"/>
 *       &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}TextTruncationAttributes2"/>
 *       &lt;attribute name="reverseCategoryOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="labelDisplayType" default="nested">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="nested"/>
 *             &lt;enumeration value="concat"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrdinalAxis2Type", propOrder = {

})
@XmlSeeAlso({
    V2OrdinalAxis.class
})
public class OrdinalAxis2Type {

    @XmlElement(name = "v2_axisTitle")
    protected V2AxisTitle v2AxisTitle;
    protected ReportDrills reportDrills;
    @XmlElement(name = "v2_axisLabels")
    protected V2AxisLabels v2AxisLabels;
    @XmlElement(name = "v2_axisLine")
    protected V2AxisLine v2AxisLine;
    @XmlElement(name = "v2_majorGridlines")
    protected V2MajorGridlines v2MajorGridlines;
    @XmlElement(name = "v2_minorGridlines")
    protected V2MinorGridlines v2MinorGridlines;
    @XmlElement(name = "v2_majorBackgroundColors")
    protected V2MajorBackgroundColors v2MajorBackgroundColors;
    @XmlElement(name = "XMLAttributes")
    protected XMLAttributes xmlAttributes;
    @XmlAttribute(name = "reverseCategoryOrder")
    protected Boolean reverseCategoryOrder;
    @XmlAttribute(name = "labelDisplayType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String labelDisplayType;
    @XmlAttribute(name = "numberOfMinorIntervals")
    protected BigInteger numberOfMinorIntervals;
    @XmlAttribute(name = "showInMatrix")
    protected Boolean showInMatrix;
    @XmlAttribute(name = "autoTruncation")
    protected Boolean autoTruncation;
    @XmlAttribute(name = "truncationText")
    protected String truncationText;
    @XmlAttribute(name = "manualTruncationMaxChars")
    @XmlSchemaType(name = "unsignedInt")
    protected Long manualTruncationMaxChars;

    /**
     * Axis title.  This can either be specified or automatically generated by the server.
     * 
     * @return
     *     possible object is
     *     {@link V2AxisTitle }
     *     
     */
    public V2AxisTitle getV2AxisTitle() {
        return v2AxisTitle;
    }

    /**
     * Sets the value of the v2AxisTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2AxisTitle }
     *     
     */
    public void setV2AxisTitle(V2AxisTitle value) {
        this.v2AxisTitle = value;
    }

    /**
     * Gets the value of the reportDrills property.
     * 
     * @return
     *     possible object is
     *     {@link ReportDrills }
     *     
     */
    public ReportDrills getReportDrills() {
        return reportDrills;
    }

    /**
     * Sets the value of the reportDrills property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportDrills }
     *     
     */
    public void setReportDrills(ReportDrills value) {
        this.reportDrills = value;
    }

    /**
     * Gets the value of the v2AxisLabels property.
     * 
     * @return
     *     possible object is
     *     {@link V2AxisLabels }
     *     
     */
    public V2AxisLabels getV2AxisLabels() {
        return v2AxisLabels;
    }

    /**
     * Sets the value of the v2AxisLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2AxisLabels }
     *     
     */
    public void setV2AxisLabels(V2AxisLabels value) {
        this.v2AxisLabels = value;
    }

    /**
     * If this element is not present no axis line will be rendered.
     * 
     * @return
     *     possible object is
     *     {@link V2AxisLine }
     *     
     */
    public V2AxisLine getV2AxisLine() {
        return v2AxisLine;
    }

    /**
     * Sets the value of the v2AxisLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2AxisLine }
     *     
     */
    public void setV2AxisLine(V2AxisLine value) {
        this.v2AxisLine = value;
    }

    /**
     * Gets the value of the v2MajorGridlines property.
     * 
     * @return
     *     possible object is
     *     {@link V2MajorGridlines }
     *     
     */
    public V2MajorGridlines getV2MajorGridlines() {
        return v2MajorGridlines;
    }

    /**
     * Sets the value of the v2MajorGridlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2MajorGridlines }
     *     
     */
    public void setV2MajorGridlines(V2MajorGridlines value) {
        this.v2MajorGridlines = value;
    }

    /**
     * Gets the value of the v2MinorGridlines property.
     * 
     * @return
     *     possible object is
     *     {@link V2MinorGridlines }
     *     
     */
    public V2MinorGridlines getV2MinorGridlines() {
        return v2MinorGridlines;
    }

    /**
     * Sets the value of the v2MinorGridlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2MinorGridlines }
     *     
     */
    public void setV2MinorGridlines(V2MinorGridlines value) {
        this.v2MinorGridlines = value;
    }

    /**
     * Gets the value of the v2MajorBackgroundColors property.
     * 
     * @return
     *     possible object is
     *     {@link V2MajorBackgroundColors }
     *     
     */
    public V2MajorBackgroundColors getV2MajorBackgroundColors() {
        return v2MajorBackgroundColors;
    }

    /**
     * Sets the value of the v2MajorBackgroundColors property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2MajorBackgroundColors }
     *     
     */
    public void setV2MajorBackgroundColors(V2MajorBackgroundColors value) {
        this.v2MajorBackgroundColors = value;
    }

    /**
     * Gets the value of the xmlAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAttributes }
     *     
     */
    public XMLAttributes getXMLAttributes() {
        return xmlAttributes;
    }

    /**
     * Sets the value of the xmlAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAttributes }
     *     
     */
    public void setXMLAttributes(XMLAttributes value) {
        this.xmlAttributes = value;
    }

    /**
     * Gets the value of the reverseCategoryOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReverseCategoryOrder() {
        if (reverseCategoryOrder == null) {
            return false;
        } else {
            return reverseCategoryOrder;
        }
    }

    /**
     * Sets the value of the reverseCategoryOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReverseCategoryOrder(Boolean value) {
        this.reverseCategoryOrder = value;
    }

    /**
     * Gets the value of the labelDisplayType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelDisplayType() {
        if (labelDisplayType == null) {
            return "nested";
        } else {
            return labelDisplayType;
        }
    }

    /**
     * Sets the value of the labelDisplayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelDisplayType(String value) {
        this.labelDisplayType = value;
    }

    /**
     * Gets the value of the numberOfMinorIntervals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfMinorIntervals() {
        if (numberOfMinorIntervals == null) {
            return new BigInteger("2");
        } else {
            return numberOfMinorIntervals;
        }
    }

    /**
     * Sets the value of the numberOfMinorIntervals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfMinorIntervals(BigInteger value) {
        this.numberOfMinorIntervals = value;
    }

    /**
     * Gets the value of the showInMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowInMatrix() {
        if (showInMatrix == null) {
            return true;
        } else {
            return showInMatrix;
        }
    }

    /**
     * Sets the value of the showInMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowInMatrix(Boolean value) {
        this.showInMatrix = value;
    }

    /**
     * Gets the value of the autoTruncation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoTruncation() {
        if (autoTruncation == null) {
            return true;
        } else {
            return autoTruncation;
        }
    }

    /**
     * Sets the value of the autoTruncation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoTruncation(Boolean value) {
        this.autoTruncation = value;
    }

    /**
     * Gets the value of the truncationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruncationText() {
        if (truncationText == null) {
            return "...";
        } else {
            return truncationText;
        }
    }

    /**
     * Sets the value of the truncationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruncationText(String value) {
        this.truncationText = value;
    }

    /**
     * Gets the value of the manualTruncationMaxChars property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getManualTruncationMaxChars() {
        if (manualTruncationMaxChars == null) {
            return  50L;
        } else {
            return manualTruncationMaxChars;
        }
    }

    /**
     * Sets the value of the manualTruncationMaxChars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setManualTruncationMaxChars(Long value) {
        this.manualTruncationMaxChars = value;
    }

}
