//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_label" minOccurs="0"/>
 *         &lt;element name="v2_topPosition" type="{http://developer.cognos.com/schemas/report/11.0/}NumericPositionType2"/>
 *         &lt;element name="v2_bottomPosition" type="{http://developer.cognos.com/schemas/report/11.0/}NumericPositionType2"/>
 *         &lt;element name="v2_leftPosition" type="{http://developer.cognos.com/schemas/report/11.0/}NumericPositionType2"/>
 *         &lt;element name="v2_rightPosition" type="{http://developer.cognos.com/schemas/report/11.0/}NumericPositionType2"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}propertyList" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}masterDetailLinks" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}XMLAttributes" minOccurs="0"/>
 *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}conditionalRender" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attGroup ref="{http://developer.cognos.com/schemas/report/11.0/}LabelLocation"/>
 *       &lt;attribute name="refQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "v2_numericColoredRegion")
public class V2NumericColoredRegion {

    @XmlElement(name = "v2_fillEffect", required = true)
    protected V2FillEffect v2FillEffect;
    @XmlElement(name = "v2_label")
    protected ChartTextLegendLabel2 v2Label;
    @XmlElement(name = "v2_topPosition", required = true)
    protected NumericPositionType2 v2TopPosition;
    @XmlElement(name = "v2_bottomPosition", required = true)
    protected NumericPositionType2 v2BottomPosition;
    @XmlElement(name = "v2_leftPosition", required = true)
    protected NumericPositionType2 v2LeftPosition;
    @XmlElement(name = "v2_rightPosition", required = true)
    protected NumericPositionType2 v2RightPosition;
    protected PropertyList propertyList;
    protected MasterDetailLinks masterDetailLinks;
    @XmlElement(name = "XMLAttributes")
    protected XMLAttributes xmlAttributes;
    protected ConditionalRender conditionalRender;
    @XmlAttribute(name = "refQuery", required = true)
    protected String refQuery;
    @XmlAttribute(name = "labelLocation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String labelLocation;

    /**
     * Gets the value of the v2FillEffect property.
     * 
     * @return
     *     possible object is
     *     {@link V2FillEffect }
     *     
     */
    public V2FillEffect getV2FillEffect() {
        return v2FillEffect;
    }

    /**
     * Sets the value of the v2FillEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2FillEffect }
     *     
     */
    public void setV2FillEffect(V2FillEffect value) {
        this.v2FillEffect = value;
    }

    /**
     * Generic authored label.
     * 
     * @return
     *     possible object is
     *     {@link ChartTextLegendLabel2 }
     *     
     */
    public ChartTextLegendLabel2 getV2Label() {
        return v2Label;
    }

    /**
     * Sets the value of the v2Label property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChartTextLegendLabel2 }
     *     
     */
    public void setV2Label(ChartTextLegendLabel2 value) {
        this.v2Label = value;
    }

    /**
     * Gets the value of the v2TopPosition property.
     * 
     * @return
     *     possible object is
     *     {@link NumericPositionType2 }
     *     
     */
    public NumericPositionType2 getV2TopPosition() {
        return v2TopPosition;
    }

    /**
     * Sets the value of the v2TopPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericPositionType2 }
     *     
     */
    public void setV2TopPosition(NumericPositionType2 value) {
        this.v2TopPosition = value;
    }

    /**
     * Gets the value of the v2BottomPosition property.
     * 
     * @return
     *     possible object is
     *     {@link NumericPositionType2 }
     *     
     */
    public NumericPositionType2 getV2BottomPosition() {
        return v2BottomPosition;
    }

    /**
     * Sets the value of the v2BottomPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericPositionType2 }
     *     
     */
    public void setV2BottomPosition(NumericPositionType2 value) {
        this.v2BottomPosition = value;
    }

    /**
     * Gets the value of the v2LeftPosition property.
     * 
     * @return
     *     possible object is
     *     {@link NumericPositionType2 }
     *     
     */
    public NumericPositionType2 getV2LeftPosition() {
        return v2LeftPosition;
    }

    /**
     * Sets the value of the v2LeftPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericPositionType2 }
     *     
     */
    public void setV2LeftPosition(NumericPositionType2 value) {
        this.v2LeftPosition = value;
    }

    /**
     * Gets the value of the v2RightPosition property.
     * 
     * @return
     *     possible object is
     *     {@link NumericPositionType2 }
     *     
     */
    public NumericPositionType2 getV2RightPosition() {
        return v2RightPosition;
    }

    /**
     * Sets the value of the v2RightPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericPositionType2 }
     *     
     */
    public void setV2RightPosition(NumericPositionType2 value) {
        this.v2RightPosition = value;
    }

    /**
     * Gets the value of the propertyList property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyList }
     *     
     */
    public PropertyList getPropertyList() {
        return propertyList;
    }

    /**
     * Sets the value of the propertyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyList }
     *     
     */
    public void setPropertyList(PropertyList value) {
        this.propertyList = value;
    }

    /**
     * Gets the value of the masterDetailLinks property.
     * 
     * @return
     *     possible object is
     *     {@link MasterDetailLinks }
     *     
     */
    public MasterDetailLinks getMasterDetailLinks() {
        return masterDetailLinks;
    }

    /**
     * Sets the value of the masterDetailLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterDetailLinks }
     *     
     */
    public void setMasterDetailLinks(MasterDetailLinks value) {
        this.masterDetailLinks = value;
    }

    /**
     * Gets the value of the xmlAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link XMLAttributes }
     *     
     */
    public XMLAttributes getXMLAttributes() {
        return xmlAttributes;
    }

    /**
     * Sets the value of the xmlAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLAttributes }
     *     
     */
    public void setXMLAttributes(XMLAttributes value) {
        this.xmlAttributes = value;
    }

    /**
     * Gets the value of the conditionalRender property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionalRender }
     *     
     */
    public ConditionalRender getConditionalRender() {
        return conditionalRender;
    }

    /**
     * Sets the value of the conditionalRender property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionalRender }
     *     
     */
    public void setConditionalRender(ConditionalRender value) {
        this.conditionalRender = value;
    }

    /**
     * Gets the value of the refQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefQuery() {
        return refQuery;
    }

    /**
     * Sets the value of the refQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefQuery(String value) {
        this.refQuery = value;
    }

    /**
     * Gets the value of the labelLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelLocation() {
        if (labelLocation == null) {
            return "legend";
        } else {
            return labelLocation;
        }
    }

    /**
     * Sets the value of the labelLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelLocation(String value) {
        this.labelLocation = value;
    }

}
