//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="v2_progressivePositiveValueFill" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="v2_progressiveNegativeValueFill" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="v2_progressiveFirstValueFill" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="v2_progressiveTotalValueFill" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
 *                   &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "v2_progressivePalette")
public class V2ProgressivePalette {

    @XmlElement(name = "v2_progressivePositiveValueFill")
    protected V2ProgressivePalette.V2ProgressivePositiveValueFill v2ProgressivePositiveValueFill;
    @XmlElement(name = "v2_progressiveNegativeValueFill")
    protected V2ProgressivePalette.V2ProgressiveNegativeValueFill v2ProgressiveNegativeValueFill;
    @XmlElement(name = "v2_progressiveFirstValueFill")
    protected V2ProgressivePalette.V2ProgressiveFirstValueFill v2ProgressiveFirstValueFill;
    @XmlElement(name = "v2_progressiveTotalValueFill")
    protected V2ProgressivePalette.V2ProgressiveTotalValueFill v2ProgressiveTotalValueFill;

    /**
     * Gets the value of the v2ProgressivePositiveValueFill property.
     * 
     * @return
     *     possible object is
     *     {@link V2ProgressivePalette.V2ProgressivePositiveValueFill }
     *     
     */
    public V2ProgressivePalette.V2ProgressivePositiveValueFill getV2ProgressivePositiveValueFill() {
        return v2ProgressivePositiveValueFill;
    }

    /**
     * Sets the value of the v2ProgressivePositiveValueFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2ProgressivePalette.V2ProgressivePositiveValueFill }
     *     
     */
    public void setV2ProgressivePositiveValueFill(V2ProgressivePalette.V2ProgressivePositiveValueFill value) {
        this.v2ProgressivePositiveValueFill = value;
    }

    /**
     * Gets the value of the v2ProgressiveNegativeValueFill property.
     * 
     * @return
     *     possible object is
     *     {@link V2ProgressivePalette.V2ProgressiveNegativeValueFill }
     *     
     */
    public V2ProgressivePalette.V2ProgressiveNegativeValueFill getV2ProgressiveNegativeValueFill() {
        return v2ProgressiveNegativeValueFill;
    }

    /**
     * Sets the value of the v2ProgressiveNegativeValueFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2ProgressivePalette.V2ProgressiveNegativeValueFill }
     *     
     */
    public void setV2ProgressiveNegativeValueFill(V2ProgressivePalette.V2ProgressiveNegativeValueFill value) {
        this.v2ProgressiveNegativeValueFill = value;
    }

    /**
     * Gets the value of the v2ProgressiveFirstValueFill property.
     * 
     * @return
     *     possible object is
     *     {@link V2ProgressivePalette.V2ProgressiveFirstValueFill }
     *     
     */
    public V2ProgressivePalette.V2ProgressiveFirstValueFill getV2ProgressiveFirstValueFill() {
        return v2ProgressiveFirstValueFill;
    }

    /**
     * Sets the value of the v2ProgressiveFirstValueFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2ProgressivePalette.V2ProgressiveFirstValueFill }
     *     
     */
    public void setV2ProgressiveFirstValueFill(V2ProgressivePalette.V2ProgressiveFirstValueFill value) {
        this.v2ProgressiveFirstValueFill = value;
    }

    /**
     * Gets the value of the v2ProgressiveTotalValueFill property.
     * 
     * @return
     *     possible object is
     *     {@link V2ProgressivePalette.V2ProgressiveTotalValueFill }
     *     
     */
    public V2ProgressivePalette.V2ProgressiveTotalValueFill getV2ProgressiveTotalValueFill() {
        return v2ProgressiveTotalValueFill;
    }

    /**
     * Sets the value of the v2ProgressiveTotalValueFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link V2ProgressivePalette.V2ProgressiveTotalValueFill }
     *     
     */
    public void setV2ProgressiveTotalValueFill(V2ProgressivePalette.V2ProgressiveTotalValueFill value) {
        this.v2ProgressiveTotalValueFill = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class V2ProgressiveFirstValueFill {

        @XmlElement(name = "v2_fillEffect", required = true)
        protected V2FillEffect v2FillEffect;
        @XmlElement(name = "v2_chartTextLabel")
        protected V2ChartTextLabel v2ChartTextLabel;

        /**
         * Gets the value of the v2FillEffect property.
         * 
         * @return
         *     possible object is
         *     {@link V2FillEffect }
         *     
         */
        public V2FillEffect getV2FillEffect() {
            return v2FillEffect;
        }

        /**
         * Sets the value of the v2FillEffect property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2FillEffect }
         *     
         */
        public void setV2FillEffect(V2FillEffect value) {
            this.v2FillEffect = value;
        }

        /**
         * Choice between authored label and automatic label.
         * 
         * @return
         *     possible object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public V2ChartTextLabel getV2ChartTextLabel() {
            return v2ChartTextLabel;
        }

        /**
         * Sets the value of the v2ChartTextLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public void setV2ChartTextLabel(V2ChartTextLabel value) {
            this.v2ChartTextLabel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class V2ProgressiveNegativeValueFill {

        @XmlElement(name = "v2_fillEffect", required = true)
        protected V2FillEffect v2FillEffect;
        @XmlElement(name = "v2_chartTextLabel")
        protected V2ChartTextLabel v2ChartTextLabel;

        /**
         * Gets the value of the v2FillEffect property.
         * 
         * @return
         *     possible object is
         *     {@link V2FillEffect }
         *     
         */
        public V2FillEffect getV2FillEffect() {
            return v2FillEffect;
        }

        /**
         * Sets the value of the v2FillEffect property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2FillEffect }
         *     
         */
        public void setV2FillEffect(V2FillEffect value) {
            this.v2FillEffect = value;
        }

        /**
         * Choice between authored label and automatic label.
         * 
         * @return
         *     possible object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public V2ChartTextLabel getV2ChartTextLabel() {
            return v2ChartTextLabel;
        }

        /**
         * Sets the value of the v2ChartTextLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public void setV2ChartTextLabel(V2ChartTextLabel value) {
            this.v2ChartTextLabel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class V2ProgressivePositiveValueFill {

        @XmlElement(name = "v2_fillEffect", required = true)
        protected V2FillEffect v2FillEffect;
        @XmlElement(name = "v2_chartTextLabel")
        protected V2ChartTextLabel v2ChartTextLabel;

        /**
         * Gets the value of the v2FillEffect property.
         * 
         * @return
         *     possible object is
         *     {@link V2FillEffect }
         *     
         */
        public V2FillEffect getV2FillEffect() {
            return v2FillEffect;
        }

        /**
         * Sets the value of the v2FillEffect property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2FillEffect }
         *     
         */
        public void setV2FillEffect(V2FillEffect value) {
            this.v2FillEffect = value;
        }

        /**
         * Choice between authored label and automatic label.
         * 
         * @return
         *     possible object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public V2ChartTextLabel getV2ChartTextLabel() {
            return v2ChartTextLabel;
        }

        /**
         * Sets the value of the v2ChartTextLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public void setV2ChartTextLabel(V2ChartTextLabel value) {
            this.v2ChartTextLabel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_fillEffect"/>
     *         &lt;element ref="{http://developer.cognos.com/schemas/report/11.0/}v2_chartTextLabel" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class V2ProgressiveTotalValueFill {

        @XmlElement(name = "v2_fillEffect", required = true)
        protected V2FillEffect v2FillEffect;
        @XmlElement(name = "v2_chartTextLabel")
        protected V2ChartTextLabel v2ChartTextLabel;

        /**
         * Gets the value of the v2FillEffect property.
         * 
         * @return
         *     possible object is
         *     {@link V2FillEffect }
         *     
         */
        public V2FillEffect getV2FillEffect() {
            return v2FillEffect;
        }

        /**
         * Sets the value of the v2FillEffect property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2FillEffect }
         *     
         */
        public void setV2FillEffect(V2FillEffect value) {
            this.v2FillEffect = value;
        }

        /**
         * Choice between authored label and automatic label.
         * 
         * @return
         *     possible object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public V2ChartTextLabel getV2ChartTextLabel() {
            return v2ChartTextLabel;
        }

        /**
         * Sets the value of the v2ChartTextLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link V2ChartTextLabel }
         *     
         */
        public void setV2ChartTextLabel(V2ChartTextLabel value) {
            this.v2ChartTextLabel = value;
        }

    }

}
