//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.28 at 01:59:17 PM AEDT 
//


package V5_report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://developer.cognos.com/schemas/report/11.0/}vizPropertyValuesGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vizPropertyValuesGroup"
})
@XmlRootElement(name = "vizPropertyValues")
public class VizPropertyValues {

    @XmlElements({
        @XmlElement(name = "vizPropertyValue", type = VizPropertyValues.VizPropertyValue.class),
        @XmlElement(name = "vizPropertyGroupValues", type = VizPropertyValues.VizPropertyGroupValues.class)
    })
    protected List<Object> vizPropertyValuesGroup;

    /**
     * Gets the value of the vizPropertyValuesGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vizPropertyValuesGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVizPropertyValuesGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VizPropertyValues.VizPropertyValue }
     * {@link VizPropertyValues.VizPropertyGroupValues }
     * 
     * 
     */
    public List<Object> getVizPropertyValuesGroup() {
        if (vizPropertyValuesGroup == null) {
            vizPropertyValuesGroup = new ArrayList<Object>();
        }
        return this.vizPropertyValuesGroup;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://developer.cognos.com/schemas/report/11.0/}vizPropertyValuesGroup" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vizPropertyValuesGroup"
    })
    public static class VizPropertyGroupValues {

        @XmlElements({
            @XmlElement(name = "vizPropertyValue", type = VizPropertyValues.VizPropertyValue.class),
            @XmlElement(name = "vizPropertyGroupValues", type = VizPropertyValues.VizPropertyGroupValues.class)
        })
        protected List<Object> vizPropertyValuesGroup;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the vizPropertyValuesGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vizPropertyValuesGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVizPropertyValuesGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VizPropertyValues.VizPropertyValue }
         * {@link VizPropertyValues.VizPropertyGroupValues }
         * 
         * 
         */
        public List<Object> getVizPropertyValuesGroup() {
            if (vizPropertyValuesGroup == null) {
                vizPropertyValuesGroup = new ArrayList<Object>();
            }
            return this.vizPropertyValuesGroup;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://developer.cognos.com/schemas/report/11.0/>TextType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class VizPropertyValue {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * A simple text type that preserves whitespace
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
